# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcMainFrame(wx.Frame):
#!XRCED:begin-block:xrcMainFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcMainFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MainFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_MENU, self.OnMenu_AddMenuItem, id=xrc.XRCID('AddMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_SubtractMenuItem, id=xrc.XRCID('SubtractMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_MultiplyMenuItem, id=xrc.XRCID('MultiplyMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_DivideMenuItem, id=xrc.XRCID('DivideMenuItem'))

#!XRCED:begin-block:xrcMainFrame.OnMenu_AddMenuItem
    def OnMenu_AddMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_AddMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_AddMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_SubtractMenuItem
    def OnMenu_SubtractMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_SubtractMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_SubtractMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_MultiplyMenuItem
    def OnMenu_MultiplyMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_MultiplyMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_MultiplyMenuItem        

#!XRCED:begin-block:xrcMainFrame.OnMenu_DivideMenuItem
    def OnMenu_DivideMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_DivideMenuItem()"
#!XRCED:end-block:xrcMainFrame.OnMenu_DivideMenuItem        


class xrcMainPanel(wx.Panel):
#!XRCED:begin-block:xrcMainPanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcMainPanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "MainPanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('calc.xrc')
